### ISSUE TITLE
best_score.sh file is missing

### ISSUE THREAD

**Issue by Satishpas2** [hitachi-speech/EEND#1]
model is training properly.
But its ending with 
------------
inference at exp/diarize/infer/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train.avg8-10.infer
scoring at exp/diarize/scoring/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train.avg8-10.infer
./run.sh: line 147: best_score.sh: command not found
 Could you plz tell where to find best_score.sh

**Comment by yubouf** [comment]
You can find the script at `../../../utils/best_score.sh`.
I believe the `run.sh` could find the path to `../../../utils` through `./path.sh` and `tools/env.sh` if tools made correctly.
