### ISSUE TITLE
Confusion about the calculation of DER

### ISSUE THREAD

**Issue by 875441459** [hitachi-speech/EEND#10]
In general, diarization tasks tolerate 250ms diar-error at the start and the end of each segment, but the function "calc_diarization_error()" in "model.py" seems do not take it into account. Did I miss something that concerns the "tolerance principle"?

**Comment by hshota0530** [comment]
`calc_diarization_error()` is a function to monitor DERs during training, and as you mentioned it doesn't consider the collar torelance.
Our final evaluation is conducted, e.g., [here](https://github.com/hitachi-speech/EEND/blob/master/egs/callhome/v1/run.sh#L237), which allows 250 ms of collar torelance.

**Comment by 875441459** [comment]
OK, I got it. Thank you~
