### ISSUE TITLE
Question about shuffle

### ISSUE THREAD

**Issue by takenori-y** [hitachi-speech/EEND#13]
In the [implementation](https://github.com/hitachi-speech/EEND/blob/ddf4df4da55a493f550b6c45689b2d60a716c06d/eend/chainer_backend/diarization_dataset.py#L99), acoustic features rather than embeddings are shuffled during training. Is it ok? The positional encoding for the Transformer-based encoder seem to be meaningless feature.

**Comment by hshota0530** [comment]
Thank you for your interest!
We created the positional encoding [here](https://github.com/hitachi-speech/EEND/blob/master/eend/chainer_backend/transformer.py#L131), but actually, it is not used in our model so it's ok to shuffle acoustic features in the dataloader.
We reported in [our ASRU 2019 paper](https://arxiv.org/pdf/1909.06247.pdf) that we did not use positional encodings as below:
> The architecture of the encoder block is depicted in Fig. 2. This configuration of the encoder block is almost the same as the one in the Speech-Transformer introduced in [44], but without positional encoding.

I'm sorry for the confusion.

**Comment by takenori-y** [comment]
Ah, I see. Thank you for answering my question.
