### ISSUE TITLE
Makefile cupy-cuda chainer

### ISSUE THREAD

**Issue by himanshisyadav** [hitachi-speech/EEND#17]
In the Makefile, I am not sure what line 36 is trying to do. 

I get the following error:

`miniconda3/envs/eend/bin/pip install cupy-cuda10==6.2.0 chainer==6.2.0
ERROR: Could not find a version that satisfies the requirement cupy-cuda10==6.2.0
ERROR: No matching distribution found for cupy-cuda10==6.2.0
`

**Comment by yubouf** [comment]
I guess you have cuda 10.0 or 10.2. The line#36 should try to get cupy-cuda100 or cupy-cuda102.

https://github.com/hitachi-speech/EEND/blob/ddf4df4da55a493f550b6c45689b2d60a716c06d/tools/Makefile#L10
This line might have an issue. I found the awk part should be changed as follows:
```Makefile
CUDA_VERSION := $(shell $(CUDA_PATH)/bin/nvcc --version | tail -n1 | awk '{print substr($$5,1,length($$5)-1)}')
```

**Comment by himanshisyadav** [comment]
I changed line 10 as recommended. I also modified line 36 to:

`miniconda3/envs/eend/bin/pip install cupy-cuda$(subst .,,$(CUDA_VERSION)) chainer==6.2.0`
