### ISSUE TITLE
The SA-EEND-EDA experiment DER result on mini_librispeech

### ISSUE THREAD

**Issue by erichong0318** [hitachi-speech/EEND#20]
Excellent code!
I have one question that I tried the experiment on egs/mini_librispeech, but I got the DER about 30.34.
I choose mini_librispeech due to lack of LDC data,.
I directly trained SA-EEND-EDA on mini_librispeech set (set "speaker_num=2" in train.yaml) and then run the infering (also set "speaker_num=2" in infer.yaml) and scoring command.
Other conf remain unchanged, so the epoch is 100.
I wondering that maybe I did something wrong.
If you have already tried this experimet on mini_librispeech, can you tell me about your final DER on mini_librispeech?
I  want to know whether I done this experiment correct or not.
Thanks a lot!!

**Comment by yfchen97** [comment]
Can you tell in detail how to run EEND using mini-lrispeech from loading data to processing data.I'm having the trouble with the data processing part of the input. Thank you very much for your help!

**Comment by yfchen97** [comment]
I have the same problem. Have you solved it?

**Comment by erichong0318** [comment]
What's the  trouble  you meet?

yfchen97 ***@***.***> 於 2021年6月15日 週二 上午9:45寫道：

**Comment by hshota0530** [comment]
I got 29.84% DER, so there's probably nothing wrong with your experiments.
