### ISSUE TITLE
PositionalEncoding does not used?

### ISSUE THREAD

**Issue by kli017** [hitachi-speech/EEND#38]
Hello, in transformer.py I found that the pos_enc was initialized in the encoder but it was not used ind the forward?

**Comment by DiLiangWU** [comment]
![image](https://user-images.githubusercontent.com/88640484/155708629-fee0d3dc-8f17-4748-91b0-1fabfe519613.png)

**Comment by DiLiangWU** [comment]
They did not use positional encoding, as described in paper.
[2] Yusuke Fujita, Naoyuki Kanda, Shota Horiguchi, Yawen Xue, Kenji Nagamatsu, Shinji Watanabe, " End-to-End Neural Speaker Diarization with Self-attention," Proc. ASRU, pp. 296-303, 2019
![image](https://user-images.githubusercontent.com/88640484/155708897-00932b46-1e3c-4e91-bff6-d163feb124ef.png)
