### ISSUE TITLE
Question about CUDA toolkit version

### ISSUE THREAD

**Issue by msh9184** [hitachi-speech/EEND#43]
Hi, thanks a lot for your work.
I have the question about CUDA toolkit version.

My experiment setting is based on NVIDIA RTX 3090 GPU, so I have to use CUDA toolkit higher than 11.1 version.
But the dependencies for your repo seem to require the CUDA Toolkit version from 8.0 to 10.1.

Can I run your recipe on the CUDA toolkit of higher than 11.1 version?

**Comment by msh9184** [comment]
No problem.

**Comment by yhy929** [comment]
Hi, @msh9184  . I understand that you seem to use 3090 server to run the EEND project, did you run it successfully? Does CUDA toolkit version affect program running? When I tried to run it,I have finished task about run_prep.sh ,but when i start to run the run.sh,it will appear some problems just like this:
training model at exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train.
run.pl: job failed, log is in exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train/.work/train.log
And the log document is empty ，do you  know how to solove it？I really hope to get your help.

**Comment by lz-hust** [comment]
> Hi, [@msh9184](https://github.com/msh9184) . I understand that you seem to use 3090 server to run the EEND project, did you run it successfully? Does CUDA toolkit version affect program running? When I tried to run it,I have finished task about run_prep.sh ,but when i start to run the run.sh,it will appear some problems just like this:你好。我知道您似乎使用 3090 服务器来运行 EEND 项目，您成功运行了吗？CUDA 工具包版本会影响程序运行吗？当我尝试运行它时，我已经完成了大约 run_prep.sh 的任务，但是当我开始运行 run.sh 时，它会出现一些问题，就像这样： training model at exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train.训练模型位于 exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train。 run.pl: job failed, log is in exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train/.work/train.logrun.pl：作业失败，日志位于 exp/diarize/model/train_clean_5_ns2_beta2_500.dev_clean_2_ns2_beta2_500.train/.work/train.log And the log document is empty ，do you know how to solove it？I really hope to get your help.而且日志文档是空的，你知道怎么喜欢它吗？我真的希望得到你的帮助。

Just like you, I am using CUDA version 11.2, so I cannot use the cupy-cuda and chainer libraries in version 6.2.0 as specified in the Makefile. As a result, I am unable to start training after preparing the data, and I encounter the same error message as you. After checking the logs, I found that the issue was indeed due to the incompatibility between the cupy-cuda and chainer libraries. Have you managed to solve this problem in the end? Thank you
