### ISSUE TITLE
Tcl_AsyncDelete error

### ISSUE THREAD

**Issue by AntonOkhotnikov** [hitachi-speech/EEND#5]
Hello, some time ago I caught the next error while training:
```
   0.55256 iters/sec. Estimated time to finish: 19 days, 0:00:23.591611.
     total [####..............................................]  9.99%
this epoch [#################################################.] 99.30%
    100700 iter, 9 epoch / 100 epochs
   0.59537 iters/sec. Estimated time to finish: 17 days, 15:10:34.544256.
Tcl_AsyncDelete: async handler deleted by the wrong thread
# Accounting: time=221865 threads=1
```
Do you have any ideas of why this could happen? Stackoverflow says that `matplotlib` should use `'Agg'` backend, and it does.

**Comment by yubouf** [comment]
I don't know the reason. If it is related to `matplotlib`,
stopping graph plots by commenting out below may be a workaround.
https://github.com/hitachi-speech/EEND/blob/9a0f211ce7e377eaea242490c3d7ec0f6adab8af/eend/chainer_backend/train.py#L197-L205

**Comment by AntonOkhotnikov** [comment]
@yubouf Thank you so much, I will try it

**Comment by AntonOkhotnikov** [comment]
@yubouf The suggested solution helped to overcome this issue, so I'm closing the issue now. Thanks again
