### ISSUE TITLE
Experiment results on multiple speakers dataset

### ISSUE THREAD

**Issue by mcompute** [hitachi-speech/EEND#6]
Great paper! I enjoy reading it and like the idea of having a simple model to solving speaker diarization problem.

I do noticed that your model can classify multiple speakers and, wonder if you have benchmark your model performance against state-of-the-art techniques on dataset with more than 2 speakers.
Appreciate if can you share the experiment results on dataset with larger set of speakers. :-)

**Comment by priyankagutte** [comment]
Hi..
Is pre-trained model available for this?

**Comment by yubouf** [comment]
Sorry for not respond it.
We have done experiments with more than 2 speakers, using CALLHOME dataset.
https://arxiv.org/abs/2005.09921
https://arxiv.org/abs/2006.01796
Some implementations based on these two papers will be available.

@priyankagutte we are thinking of providing the pretrained model, but it should be trained with free datasets. Unfortunately, no good models are available for this purpose so far.

**Comment by 875441459** [comment]
Hi, So can we use a multi-talker dataset to train a 2-speaker diarization system? (Extracting everyone's  utterance and the mix them in a way like papers do)

**Comment by sw005320** [comment]
Yes. The recipe directory in the repository also provides a [script](https://github.com/hitachi-speech/EEND/blob/master/egs/callhome/v1/run_prepare_shared.sh) of how to mix them.

**Comment by 875441459** [comment]
OK, thanks for your replying~
