### ISSUE TITLE
Confusion about the store of uttid

### ISSUE THREAD

**Issue by 875441459** [hitachi-speech/EEND#9]
hi, I'm a little confused about the calculation and store of uttid. In make_mixture.py, when calculating the uttid, it multiples 100, like 
uttid = '{}_{}_{:07d}_{:07d}'.format(spkid, recid, int(startpos / args.rate * 100),int(endpos / args.rate * 100)).But why not do sth like str(int(startpos / args.rate *1000)/1000) to store it more precisely?

**Comment by yubouf** [comment]
We followed the kaldi-style. https://kaldi-asr.org/doc/data_prep.html
Multiply by 100 means the frame index when using 10 msec frame shift.
I think this resolution is sufficient for our tasks.

**Comment by 875441459** [comment]
Thanks, I'll check the website.
